from pathlib import Path
path = Path('/home/ubuntu/controle-viagens/client/src/pages/Home.tsx')
text = path.read_text()
old_trip = '["Data", "Aba mensal", "Veículo", "Motorista", "Destino", "Ação"].map(head => <th key={head} className="px-4 py-3 text-[10px] uppercase tracking-[0.12em] text-[#75827f] font-bold whitespace-nowrap">{head}</th>)'
new_trip = '<SortHeader label="Data" sortKey="tripDate" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} /><SortHeader label="Aba mensal" sortKey="sourceSheet" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} /><SortHeader label="Veículo" sortKey="vehiclePlate" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} /><SortHeader label="Motorista" sortKey="driverName" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} /><SortHeader label="Destino" sortKey="destination" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} /><SortHeader label="Ação" sortKey="purpose" sort={tripSort} onSort={key => setTripSort(current => nextSort(current, key))} />'
old_record = '["Data/hora", "Veículo", "Evento", "Matrícula", "Motorista", "Km inicial", "Km final", "Atendimento", "Condição"].map(head => <th key={head} className="px-4 py-3 text-[10px] uppercase tracking-[0.12em] text-[#75827f] font-bold whitespace-nowrap">{head}</th>)'
new_record = '<SortHeader label="Data/hora" sortKey="recordedAt" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Veículo" sortKey="vehiclePlate" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Evento" sortKey="event" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Matrícula" sortKey="employeeId" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Motorista" sortKey="respondentName" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Km inicial" sortKey="kmInitial" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Km final" sortKey="kmFinal" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Atendimento" sortKey="serviceType" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} /><SortHeader label="Condição" sortKey="vehicleCondition" sort={recordSort} onSort={key => setRecordSort(current => nextSort(current, key))} />'
if text.count(old_trip) != 1 or text.count(old_record) != 1:
    raise SystemExit(f'headers not unique: trips={text.count(old_trip)} records={text.count(old_record)}')
text = text.replace(old_trip, new_trip).replace(old_record, new_record)
path.write_text(text)
