from pathlib import Path
p = Path('/home/ubuntu/controle-viagens/client/src/pages/Home.tsx')
t = p.read_text()
t = t.replace('  const [mobileMenu, setMobileMenu] = useState(false);', '  const [mobileMenu, setMobileMenu] = useState(false);\n  const [visitorMode, setVisitorMode] = useState(false);')
old = '  if (!user && visitorAccessQuery.data !== true) return <div className="min-h-screen bg-[#14283f] text-white flex items-center justify-center p-6 relative overflow-hidden"><div className="absolute -right-32 -top-24 h-96 w-96 rounded-full bg-[#e4684d]/20 blur-3xl" /><div className="absolute -left-24 bottom-0 h-80 w-80 rounded-full bg-[#4f8f77]/30 blur-3xl" /><Card className="w-full max-w-lg border-white/10 bg-white/10 text-white backdrop-blur-xl shadow-2xl relative"><CardContent className="p-10 md:p-14"><div className="h-12 w-12 rounded-2xl bg-[#e4684d] flex items-center justify-center mb-8"><ArrowDownUp className="h-6 w-6 rotate-45" /></div><p className="text-[#e9b5a7] uppercase tracking-[0.2em] text-xs font-semibold">Painel operacional</p><h1 className="font-display text-4xl md:text-5xl font-bold leading-tight mt-3">Controle de<br /><span className="text-[#ef876f]">Viagens.</span></h1><p className="text-white/65 mt-6 max-w-sm leading-relaxed">Acompanhe 52 meses de deslocamentos, frota e equipe em um só lugar.</p><Button onClick={() => startLogin()} size="lg" className="w-full mt-10 bg-white text-[#14283f] hover:bg-[#edf3ef] gap-2">Entrar com e-mail <ChevronDown className="h-4 w-4 -rotate-90" /></Button><p className="text-center text-xs text-white/40 mt-5">Acesso seguro para usuários cadastrados</p></CardContent></Card></div>;' 
new = '  if (!user && (visitorAccessQuery.data !== true || !visitorMode)) return <div className="min-h-screen bg-[#14283f] text-white flex items-center justify-center p-6 relative overflow-hidden"><div className="absolute -right-32 -top-24 h-96 w-96 rounded-full bg-[#e4684d]/20 blur-3xl" /><div className="absolute -left-24 bottom-0 h-80 w-80 rounded-full bg-[#4f8f77]/30 blur-3xl" /><Card className="w-full max-w-lg border-white/10 bg-white/10 text-white backdrop-blur-xl shadow-2xl relative"><CardContent className="p-10 md:p-14"><div className="h-12 w-12 rounded-2xl bg-[#e4684d] flex items-center justify-center mb-8"><ArrowDownUp className="h-6 w-6 rotate-45" /></div><p className="text-[#e9b5a7] uppercase tracking-[0.2em] text-xs font-semibold">Painel operacional</p><h1 className="font-display text-4xl md:text-5xl font-bold leading-tight mt-3">Controle de<br /><span className="text-[#ef876f]">Viagens.</span></h1><p className="text-white/65 mt-6 max-w-sm leading-relaxed">Acompanhe 52 meses de deslocamentos, frota e equipe em um só lugar.</p><Button onClick={() => startLogin()} size="lg" className="w-full mt-10 bg-white text-[#14283f] hover:bg-[#edf3ef] gap-2">Entrar com e-mail <ChevronDown className="h-4 w-4 -rotate-90" /></Button>{visitorAccessQuery.data === true && <><div className="flex items-center gap-3 my-5 text-white/35 text-xs"><div className="h-px flex-1 bg-white/15" />ou<div className="h-px flex-1 bg-white/15" /></div><Button onClick={() => setVisitorMode(true)} variant="outline" size="lg" className="w-full border-white/25 bg-white/5 text-white hover:bg-white/10">Continuar como visitante</Button><p className="text-center text-xs text-white/45 mt-3">Acesso público liberado pelo administrador</p></> }<p className="text-center text-xs text-white/40 mt-5">Use o e-mail cadastrado na aba Equipe para entrar.</p></CardContent></Card></div>;'
if old not in t:
    raise SystemExit('login gate not found')
t = t.replace(old, new)
p.write_text(t)
